<?php

/**
 * @file
 * Adds a Maestro notification to the Drupal toolbar
 */

/**
 * Implements hook_help().
 */
function maestro_toolbar_notifications_help($path, $arg) {
  switch ($path) {
    case 'admin/help#maestro_toolbar_notifications':
      $helptext  = '<h3>' . t('About') . '</h3>';
      $helptext .= '<p>' . t('A simple module that when enabled in conjunction with Maestro
        will add a menu item to the Toolbar that shows the number of Maestro notifications
        that user has. This style of notification improves the content authoring experience
        by giving the user a heads up on how many tasks they have in their queue.') . '</p>';
      $helptext .= '<h3>' . t('Configuration') . '</h3>';
      $helptext .= '<p>' .
        t('This module does not register any configuration pages. To have
            access to this module\'s functionality users must have both "Use the administration
            toolbar" and "Access Maestro Task Console" permissions. By default the notifications
            menu item will show up on the far left of the toolbar, this positioning can be
            changed with the from the !managmentpagelink.',
          array(
            '!managmentpagelink' => l('managment menu configuration page',
            'admin/structure/menu/manage/management')
          )) . '</p>';
      $helptext .= '<h3>' . t('Contributors') . '</h3>';
      $helptext .= '<p>' .
        t('This module was written by !calvintennant at !myplanetdigital',
          array(
            '!calvintennant' => l('Calvin Tennant', 'http://calvintennant.com'),
            '!myplanetdigital' => l('Myplanet Digital', 'http://myplanetdigital.com'),
          )) . '</p>';

      return $helptext;
  }
}

/**
 * Implements hook_menu().
 */
function maestro_toolbar_notifications_menu() {
  $items['admin/notifications'] = array(
    'title' => 'Notifications',
    'page callback' => 'maestro_toolbar_notifications_page',
    'access callback' => 'maestro_toolbar_notifications_access',
    'weight' => -16,
  );

  return $items;
}

/**
 * Returns true when user has permissions to both
 * 'maestro taskconsole' and 'access toolbar'.
 */
function maestro_toolbar_notifications_access() {
  if (user_access('maestro taskconsole') && user_access('access toolbar')) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_init().
 * Grabs the notifications for the current user and
 * sends them to the Drupal.settings js object.
 */
function maestro_toolbar_notifications_preprocess(&$variables, $hook) {
  if (maestro_toolbar_notifications_access()) {
    // Load maestro.moderator.inc from the maestro module.
    module_load_include('inc', 'maestro', 'maestro.moderator');

    $result = db_query(maestro_get_all_flows_data(array('myflows' => TRUE)));

    $notification_count = $result->rowCount();

    if ($notification_count == 1) {
      $notification_term = t('Notification');
    }
    else {
      $notification_term = t('Notifications');
    }
    drupal_add_js(array(
      'maestro_toolbar_notifications' => array(
        'notification' => $notification_count . ' ' . $notification_term,
      ),
    ), 'setting');
  }
}

function maestro_toolbar_notifications_page() {
  menu_set_active_item('maestro/myflows');
  return menu_execute_active_handler(NULL, FALSE);
}
