<?php

/**
 * @file
 * Adds a Maestro notification to the Druapl toolbar
 */

/**
 * Implementation of hook_menu()
 */
function maestro_toolbar_notifications_menu() {
  module_load_include('inc', 'maestro', 'maestro.moderator');
  $items['admin/notifications'] = array(
    'title' => 'Notifications',
    'page callback' => 'maestro_my_flows',
    'access arguments' => array('maestro taskconsole'),
    'weight' => -16,
  );

  return $items;
}

// Run the count function on every page load
maestro_toolbar_notifications_count();

/**
 * Grabs the notifications for the current user and 
 * sends them to the Drupal.settings js object
 */
function maestro_toolbar_notifications_count() {
  // Load maestro.moderator.inc from the maestro module.
  module_load_include('inc', 'maestro', 'maestro.moderator');

  $result = db_query(maestro_get_all_flows_data(array('myflows' => TRUE)));

  $notification_count = 0;

  foreach ($result as $record) {
    $notification_count++;
  }

  if ($notification_count == 1) {
    $notification_term = t('Notification');
  }
  else {
    $notification_term = t('Notifications');
  }
  drupal_add_js(array(
    'maestro_toolbar_notifications' => array(
      'notification' => $notification_count . ' ' . $notification_term,
    )
  ), 'setting');
}
